<a href="https://colab.research.google.com/github/Dsushmitha/Web-Scrapping-and-Data-Visualisation-with-Python/blob/main/Web_Scraping_with_Python_Starter_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Step 1: Loading modules**
Before we start scrapping the target website, we need to import some necessary modules from the system library.
*   “requests” includes the modules for sending HTTP requests to websites, the core step for web scrapping.
*   “bs4/BeautifulSoup” includes the required APIs for cleaning and formatting the data collected from the web scrapper.
*   “pandas” includes some essential functionalities for data analytics, allowing users to quickly manipulate and analyse them.
---

In [ ]:
import requests 
from bs4 import BeautifulSoup 
import pandas as pd

# **Step 2: Naïve Scrapping Method (Scrapping Whole Page)**
We will now introduce the simplest way to scrape the data from a website.
*   Define a Python "list" for every column you identified in the stock price table from Yahoo! Finance.
*   Add the URL of the target website in the code.
*   Observe the stock price table and identify the column data that will be useful. Then, use the "Inspect" feature from Chrome to show the HTML content.
*   Use for-loop to format the data collected from BeautifulSoup.


**Discussions**
1.   Try to discuss the advantages and disadvantages of the method above。
2.   If the column name of the underlying table in the website changes, does this method still work?
---

In [ ]:
# TODO: Use requests and BeautifulSoup（BS）to scrape website data
active_stocks_url = "https://in.finance.yahoo.com/most-active"
r = requests.get(active_stocks_url)
data = r.text
soup = BeautifulSoup(data)

# TODO: Define python lists for every column and get the HTML table
symbols=[]
names=[]
prices=[]
changes=[]
percentage_changes=[]
volumes=[]
market_caps=[]
price_earning_ratios=[]

In [ ]:
"""
Using the concepts of for-loop, find all the <tr> tags from "stockTable".
Every <tr> tag represent a row of stock data (saved as listing).
We need to find all the <td> tag from the "listing", and extract its info to be inserted to the relevant python list.
"""
# TODO: Fill in the relevant HTML tag in the find_all "brackets"
stocks_table = soup.find('tbody')
for listing in stocks_table.find_all('tr'):
  symbol = listing.find('td',attrs={'aria-label':'Symbol'})
  symbols.append(symbol.text)

  name = listing.find('td',attrs={'aria-label':'Name'})
  names.append(name.text)
  
  price = listing.find('td',attrs={'aria-label':"Price (intraday)"})
  prices.append(price.text)
  
  change = listing.find('td',attrs={'aria-label':'Change'})
  changes.append(change.text)
  
  percentage_change = listing.find('td',attrs={'aria-label':'% change'})
  percentage_changes.append(percentage_change.text)
  
  volume = listing.find('td',attrs={'aria-label':'Volume'})
  volumes.append(volume.text)
  
  market_cap = listing.find('td',attrs={'aria-label':'Market cap'})
  market_caps.append(market_cap.text)
  
  price_earning_ratio = listing.find('td',attrs={'aria-label':'PE ratio (TTM)'})
  price_earning_ratios.append(price_earning_ratio.text)

In [ ]:
"""
Use pandas to create a new data frame, aggregate all python lists into a single table.
You will need to know how to use Python dictionary in this part.
"""
# TODO: Display the table using a Python dataframe
df = pd.DataFrame({ "Symbol":           symbols,
                    "Name":             names,
                    "Price (intraday)": prices,
                    "Change":           changes,
                    "% change":         percentage_changes,
                    "Volume":           volumes,
                    "Market cap":       market_caps,
                    "PE ratio (TTM)":   price_earning_ratios })
df

           Symbol  ... PE ratio (TTM)
0      YESBANK.NS  ...            N/A
1          PNB.NS  ...          33.59
2         UVSL.NS  ...            N/A
3         SBIN.NS  ...          15.85
4   BANKBARODA.NS  ...          13.67
5         SAIL.NS  ...          15.55
6   IDFCFIRSTB.NS  ...          68.10
7         IDEA.NS  ...            N/A
8          IOC.NS  ...          20.80
9         BHEL.NS  ...            N/A
10        HFCL.NS  ...          24.03
11       CANBK.NS  ...           8.08
12  LAKSHVILAS.NS  ...            N/A
13   SOUTHBANK.NS  ...            N/A
14   TATAPOWER.NS  ...          33.85
15      RPOWER.NS  ...           9.20
16  NATIONALUM.NS  ...          29.24
17     JPPOWER.NS  ...            N/A
18    RTNINFRA.BO  ...            N/A
19        IDEA.BO  ...            N/A
20        IRFC.NS  ...           7.54
21  FEDERALBNK.NS  ...          10.40
22  TATAMOTORS.NS  ...            N/A
23     YESBANK.BO  ...            N/A
24         ITC.NS  ...          19.61

[25 rows x 8 columns]

# **Step 3: Naïve Scrapping Method (Scrapping Individual Rows)**
*   Copy and paste the Yahoo Finance link for currencies。
*   Use Chrome Inspector to inspect the HTML elements。

**Discussions**
1.   What is the difference of this method in terms of execution efficiency when compared to the previous method?
2.   If the row header, does this method still works?
3.   When should we use whole page scraping, when should we use individual row scraping?
---

In [ ]:
# TODO: Scrape website data and extract info into relevant Python lists
currencies_url = "https://in.finance.yahoo.com/currencies"
r = requests.get(currencies_url)
data = r.text
soup = BeautifulSoup(data)

symbols=[]
names=[]
last_prices=[]
changes=[]
percentage_changes=[]

# TODO: Find the starting and ending data-reactid，and the difference between each column
start, end, jump = 33, 449, 16
stocks_table = soup.find('tbody')
for i in range(start,end,jump):
  listing = stocks_table.find('tr',attrs={'data-reactid':i})

  symbol = listing.find('td',attrs={'data-reactid':i+1})
  symbols.append(symbol.text)

  name = listing.find('td',attrs={'data-reactid':i+3})
  names.append(name.text)
  
  last_price = listing.find('td',attrs={'data-reactid':i+5})
  last_prices.append(price.text)
  
  change = listing.find('td',attrs={'data-reactid':i+7})
  changes.append(change.text)
  
  percentage_change = listing.find('td',attrs={'data-reactid':i+9})
  percentage_changes.append(percentage_change.text)  


# TODO: Display the table using a Python dataframe
df = pd.DataFrame({ "Symbol":     symbols,
                    "Name":       names,
                    "Last price": last_prices,
                    "Change":     changes,
                    "% change":   percentage_changes })
df

      Symbol     Name Last price    Change % change
0      INR=X  USD/INR     211.50   +0.1430   +0.20%
1   EURINR=X  EUR/INR     211.50   +0.3877   +0.44%
2   GBPINR=X  GBP/INR     211.50   -0.0084   -0.01%
3   AEDINR=X  AED/INR     211.50   +0.0150   +0.08%
4   INRJPY=X  INR/JPY     211.50   -0.0032   -0.21%
5   SGDINR=X  SGD/INR     211.50   +0.1870   +0.34%
6   USDIDR=X  USD/IDR     211.50  -20.0000   -0.14%
7   USDTHB=X  USD/THB     211.50   -0.0120   -0.04%
8   USDMYR=X  USD/MYR     211.50   +0.0050   +0.12%
9   USDZAR=X  USD/ZAR     211.50   +0.0449   +0.32%
10  USDRUB=X  USD/RUB     211.50   +0.0075   +0.01%
11  AUDUSD=X  AUD/USD     211.50   -0.0007   -0.09%
12  AUDJPY=X  AUD/JPY     211.50   -0.1020   -0.12%
13  NZDUSD=X  NZD/USD     211.50   +0.0003   +0.04%
14  EURUSD=X  EUR/USD     211.50   +0.0037   +0.31%
15  EURCAD=X  EUR/CAD     211.50   +0.0026   +0.18%
16     JPY=X  USD/JPY     211.50   -0.0600   -0.06%
17  GBPUSD=X  GBP/USD     211.50   -0.0021   -0.15%
18     CHF=X  USD/CHF     211.50   -0.0003   -0.03%
19     CAD=X  USD/CAD     211.50   -0.0013   -0.11%
20  EURJPY=X  EUR/JPY     211.50   +0.2820   +0.21%
21  GBPJPY=X  GBP/JPY     211.50   -0.3070   -0.20%
22  EURGBP=X  EUR/GBP     211.50   +0.0036   +0.41%
23  EURSEK=X  EUR/SEK     211.50   +0.0176   +0.17%
24  EURCHF=X  EUR/CHF     211.50   +0.0024   +0.22%
25  EURHUF=X  EUR/HUF     211.50   -0.8800   -0.25%

# **Step 4: Header Scraping Method**
This method is an advanced scraping method. The code will automatically scrape the header so that we don't have to define the list for ourselves, making the code much simpler and cleaner.

*   Copy and paste the Yahoo Finance link of cryptocurrencies
*   Scrape the headers and put those into a python list
*   Put the relevant data into a Python dictionary
---

In [ ]:
crypto_url = "https://in.finance.yahoo.com/cryptocurrencies"
r = requests.get(crypto_url)
data = r.text
soup = BeautifulSoup(data)

# TODO: Use a Python list and Python dictionaruy to scrape all the headers
raw_data = {}
headers =[]
header_rows = soup.find('thead')
for header in header_rows.find_all('th'):
  headers.append(header.text)
  raw_data[header.text]=[]

rows = soup.find('tbody')
for row in rows.find_all('tr'):
  for index,row_data in enumerate(row.find_all('td')):
    header_value = headers[index]
    raw_data[header_value].append(row_data.text)

# TODO: Display the table using a Python dataframe
pd.DataFrame(raw_data)

       Symbol                 Name  ... 52-week range 1-day chart
0     BTC-INR          Bitcoin INR  ...
1     ETH-INR         Ethereum INR  ...
2    USDT-INR           Tether INR  ...
3     ADA-INR          Cardano INR  ...
4     BNB-INR      BinanceCoin INR  ...
5    DOGE-INR         Dogecoin INR  ...
6     XRP-INR              XRP INR  ...
7    USDC-INR          USDCoin INR  ...
8    DOT1-INR         Polkadot INR  ...
9     BCH-INR      BitcoinCash INR  ...
10   UNI3-INR          Uniswap INR  ...
11    LTC-INR         Litecoin INR  ...
12   LINK-INR        Chainlink INR  ...
13    XLM-INR          Stellar INR  ...
14  MATIC-INR     MaticNetwork INR  ...
15   SOL1-INR           Solana INR  ...
16    HEX-INR              HEX INR  ...
17    VET-INR          VeChain INR  ...
18    ETC-INR  EthereumClassic INR  ...
19  THETA-INR            THETA INR  ...
20    TRX-INR             TRON INR  ...
21    FIL-INR  FilecoinFutures INR  ...
22    EOS-INR              EOS INR  ...
23    XMR-INR           Monero INR  ...
24   AAVE-INR             Aave INR  ...

[25 rows x 12 columns]

# **Step 5: Making a generic scraping function**




We are going to turn the header method into a Python function. This function can also work for other types of financial products!

*   Define a good name for the function
*   Define input paramters and input value

---

In [ ]:
# TODO: code a generic function scrape_table

# **Concept Challenge: Scrape other products**
Try using the generic function to scrape other products in Yahoo Finance!
*   Gainers
*   Losers
*   Top ETFs
---

In [ ]:
# TODO: Try using the generic function to scrape other kind of products (e.g. cryptocurrencies)

# Step 6: Data Wrangling 

**Datatype Conversion**

This part will make use of the stock data we have collected from our web scrapper. However, the data collected are all stored as "strings". In other words, the data is regarded as textual data even if the underlying data is representing a number. We need to convert them into right formats for the chart plotting tools.

Steps in data conversion：
1.   Remove all the commas in the number data, and change columns that contain number data to floating point.
2.   Change all columns that contain dates to datetime.
3.   Recover abbreaviated numbers, for example, recover "1M" to 1000000.

In [ ]:
from datetime import datetime
def convert_column_to_float(df, columns):
# TODO: code the logic for string to float

def convert_column_to_datetime(df, columns):
# TODO: code the logic for string to datetime

def revert_scaled_number(number):
# TODO: code the logic for converting the string apreviations back to numbers

**Filtering dataframe**

- We can scrape all the active stocks easily now
- Let's try to separate them into rising and losing stocks?

In [ ]:
# TODO: first scrape the active stocks table using the web scraper function

# TODO: change the data type of the dataframe columns

# TODO: filter the dataframe by % Change (pos/neg)

**Sorting dataframe**

- It's not quite clear which stock is the top gainer/loser
- We can sort the dataframe and see it clearly

In [ ]:
rising = rising.sort_values(by=['% Change'], ascending=False)
# TODO: get the losing stocks

Finally, if you prefer, you can add back the "+/-" sign and the percentage symbol and convert back the value to string

In [ ]:
rising['% Change']='+' + rising['% Change'].astype(str) + '%'
losing['% Change']=losing['% Change'].astype(str) + '%'

In [ ]:
rising